# SITE SETTINGS
# replace with the name you want displayed on the bio (i.e. your name)
name: Ron Megason
# replace with your desired description
description: Actor
# replace with keywords you want placed in the meta keywords section of the HTML header
keywords: Actor, TV, Movies, Shows, TV Shows, IMDb
# replace with your contact email (used for the email link in the footer)
email: your_email@example.com
# replace with the production URL of your bio site
root_url: https://michaelh.org
# optionally replace with the name / extension of your image file
# i.e if using perhaps a .jpg instead, the below should be changed to `profile.jpg`
profile_image_file: profile.png

# Icon Links to display in the navbar as round icon buttons
# options, leave empty and no extra buttons will appear in
# the navbar
navbar-links:
  - fa-icon: linkedin-in
    url: https://www.linkedin.com/in/jdoeexampe/
  - fa-icon: medium-m
    url: https://medium.com/@jdoeexample
  - fa-icon: twitter
    url: https://twitter.com/jdoeexampe
navbar_list_large:
- name: About
  link: /_includes/about.html
- name: Media
  link: /_includes/media.html
- name: Gallery
  link: /_includes/headshots.html
  dropdown: &dropdown
  - name: Headshots
    link: /_includes/headshots.html
  - name: Production Photos
    link: /_includes/production
- name: Resume
    link: /_includes/resume.html
- name: Contact
    link: /_includes/contact.html

# Icon Links to display in the footer, leave empty and
# just the email link will appear (which can be removed by
# updating /_includes/footer.html)
footer-links:
  - fa-icon: github
    url: https://github.com/MichaelHDesigns/RON
  - fa-icon: stack-overflow
    url: https://www.stackoverflow.com/users/987654321

# Build settings
sass:
  sass_dir: css
